### ISSUE TITLE
module android sms Ti

### ISSUE THREAD

**Issue by 4rensycs** [omorandi/TiAndroidSMS#3]
There is nothing in the zip file.

you have another module zip file you can post?

Thanks,
R

**Comment by deckameron** [comment]
Try this one! Hope it helps!

---

 De: R Arnold notifications@github.com
Para: omorandi/TiAndroidSMS TiAndroidSMS@noreply.github.com 
Enviadas: Segunda-feira, 29 de Julho de 2013 23:27
Assunto: [TiAndroidSMS] module android sms Ti (#3)

There is nothing in the zip file.
you have another module zip file you can post?
Thanks,
R

**Comment by 4rensycs** [comment]
Hi, Sorry, But I can't see the attachment or an updated file. Did I miss it?

Thx R

**Comment by deckameron** [comment]
Sorry, I must have forgotten!
I'll be sending a link then.

modules.zip (82 KB)
https://mega.co.nz/#!BtRSiZYC!b9x4JmMGAIFba8ypwU3mMS_vpSMcGBeqKJbxkNBnoc8

My best,
Douglas

---

 De: R Arnold notifications@github.com
Para: omorandi/TiAndroidSMS TiAndroidSMS@noreply.github.com 
Cc: deckameron douglas_ufop@yahoo.com.br 
Enviadas: Terça-feira, 30 de Julho de 2013 8:46
Assunto: Re: [TiAndroidSMS] module android sms Ti (#3)

Hi, Sorry, But I can't see the attachment or an updated file. Did I miss it?
Thx R

**Comment by 4rensycs** [comment]
Thanks,

R

**Comment by 4rensycs** [comment]
Evening,

I have been able to get things where they belong but a question? Location
of 'Ti.android.sms' (via require) is not found. I am trying to build the
module I assume that needs to be done. I am guessing that this is a module
that is part of my project but building it with the components is something
that I have not done. The example that I have found is for iOS and I am
utilizing Android.

I would appreciate it if you could point me in the right direction.

Thanks kindly,
Ron

**Comment by omorandi** [comment]
This guide might help you: http://docs.appcelerator.com/titanium/latest/#!/guide/Using_a_Module
